//! Property-based tests for `phenotype-auth-core`.
//!
//! These tests complement the example-based tests in `integration.rs`
//! and the per-module `tests` blocks: instead of asserting a handful
//! of hand-picked inputs, they assert *invariants* across a wide
//! random input space using [`proptest`].
//!
//! Each property below targets a real regression class — i.e. a bug
//! that, if reintroduced, would be caught by the corresponding
//! `proptest!` case. The properties are intentionally small and
//! pure: they do not spin up async runtimes, do not touch the
//! filesystem, and do not depend on the system clock (all time
//! arguments are generated by `proptest` so the tests are
//! deterministic given a seed).
//!
//! Run with: `cargo test -p phenotype-auth-core --test property_tests`.
//! Re-run a single case with: `PROPTEST_CASES=4096 cargo test ...`.
//!
//! `expect()` in the strategy builders is intentional — a failure
//! here means a real bug in the strategy (or a fundamental
//! invariant the property is asserting), not a recoverable error.
//! `doc_markdown` is allowed because the property catalogue
//! references bare tokens like `UUIDv4` for legibility.
//!
//! ## Property catalogue
//!
//! | Property | Invariant | Regression it would catch |
//! |----------|-----------|---------------------------|
//! | `user_id_round_trips` | `parse(s).to_string() == s` for any valid UUID string | A `Display` impl that drops the curly braces (post-`uuid` upgrade) or reorders the fields |
//! | `session_id_round_trips` | same as above for `SessionId` | same as above |
//! | `session_expires_at_is_now_plus_ttl` | `Session::new(u, now, ttl).expires_at() == now + ttl` | An off-by-one in the TTL addition, a timezone bug, or accidentally subtracting instead of adding |
//! | `token_sign_verify_round_trip` | `verify(sign(t, s), s) == Ok(t)` for any 32-byte token and any secret | A flip from `&self` to `self` that consumes the token, a missing hex round-trip, a constant-time bug |
//! | `token_verify_with_wrong_secret_fails` | `verify(sign(t, s1), s2) == Err` whenever `s1 != s2` | A verify impl that short-circuits on length, or that accepts an HMAC of the empty string |
//! | `token_sign_is_deterministic` | `sign(t, s)` returns the same string on repeated calls | A non-deterministic HMAC, accidentally using a per-process nonce |
//! | `admin_can_access_everything` | `Role::Admin.can_access(p) == true` for every `Permission` variant | A refactor that moves Admin from "true" to a permission list — the kind of mistake unit tests on 1-2 permissions miss |
//! | `custom_role_can_access_matches_set` | `Role::custom(_, perms).can_access(p) == perms.contains(&p)` | A bug in the binary-search / sort / dedup path in `Role::custom` |
//! | `operator_can_access_except_billing_refund` | `Role::Operator.can_access(p) == (p != BillingRefund)` | A future "operator gets billing read" mistake (operator already gets `BillingRead`) |
//! | `permission_serde_round_trip` | `serde_json::from_str(to_string(p)) == p` for every `Permission` variant | A rename in the `#[serde(rename_all = "snake_case")]` mapping |
#![allow(clippy::expect_used, clippy::doc_markdown)]

use std::str::FromStr;

use chrono::{DateTime, Duration, Utc};
use proptest::prelude::*;
use uuid::Uuid;

use phenotype_auth_core::token::TOKEN_BYTES;
use phenotype_auth_core::{Permission, Role, Session, SessionId, Token, UserId};

// ---------------------------------------------------------------------------
// Strategies
// ---------------------------------------------------------------------------

/// Strategy that produces any of the 8 `Permission` variants. The
/// function is hand-rolled (rather than a derived `Arbitrary`) because
/// we want the values to be spread *evenly* across the enum (proptest's
/// `sample::select` of an indexed tuple) and because `Permission` does
/// not have an `Arbitrary` impl.
fn permission_strategy() -> impl Strategy<Value = Permission> {
    prop_oneof![
        Just(Permission::UsersRead),
        Just(Permission::UsersWrite),
        Just(Permission::UsersDelete),
        Just(Permission::SkillsRead),
        Just(Permission::SkillsWrite),
        Just(Permission::BillingRead),
        Just(Permission::BillingRefund),
        Just(Permission::FleetManage),
    ]
}

/// Strategy that produces a vector of `Permission` values in any
/// combination (with possible duplicates and orderings), to exercise
/// the `Role::custom` sort + dedup path.
fn permissions_vec_strategy() -> impl Strategy<Value = Vec<Permission>> {
    prop::collection::vec(permission_strategy(), 0..=8)
}

/// Strategy for a non-empty 32-byte secret (signing secret).
fn secret_strategy() -> impl Strategy<Value = Vec<u8>> {
    prop::collection::vec(any::<u8>(), 1..=64)
}

/// Strategy for the bytes that go inside a `Token`. Exactly 32 bytes.
fn token_bytes_strategy() -> impl Strategy<Value = [u8; TOKEN_BYTES]> {
    // `prop::collection::vec(_, N)` yields a `Vec<u8>` of fixed length
    // when `N` is a const. We then `try_into()` into the array form
    // expected by `Token::from_bytes`.
    prop::collection::vec(any::<u8>(), TOKEN_BYTES)
        .prop_map(|v| v.try_into().expect("vec of length TOKEN_BYTES must convert"))
}

/// Strategy for a `DateTime<Utc>`. Bounded well within the chrono
/// supported range so the addition in `Session::new` cannot overflow.
fn datetime_strategy() -> impl Strategy<Value = DateTime<Utc>> {
    // 0..=2_000_000_000 seconds since the epoch is 1970-01-01..2033-05-18.
    (0i64..=2_000_000_000).prop_map(|secs| {
        DateTime::<Utc>::from_timestamp(secs, 0).expect("secs in range 0..2e9 is always valid")
    })
}

/// Strategy for a TTL that is non-zero and small enough that
/// `now + ttl` cannot overflow chrono.
fn ttl_strategy() -> impl Strategy<Value = Duration> {
    // 1 second..=24 hours, in seconds.
    (1i64..=86_400).prop_map(Duration::seconds)
}

/// Strategy that yields a valid UUIDv4 *string*, used for the
/// `parse <-> Display` round-trip property.
fn uuid_string_strategy() -> impl Strategy<Value = String> {
    // Uuid::from_u128 takes any 128 bits; the format string is the
    // canonical hyphenated 36-char form. We don't constrain to
    // v4-specific bits because the parser accepts any UUID variant.
    any::<u128>().prop_map(|bits| Uuid::from_u128(bits).to_string())
}

/// Strategy for a `UserId` constructed from any UUIDv4-ish bits. The
/// `UserId` is `pub struct UserId(Uuid)` with a private inner, so the
/// only construction paths are `new_v4()` (random) and
/// `parse(s)`. We use the latter so the bytes are proptest-driven.
fn user_id_strategy() -> impl Strategy<Value = UserId> {
    uuid_string_strategy().prop_map(|s| UserId::parse(&s).expect("uuid_string_strategy always yields a valid UUID"))
}

// ---------------------------------------------------------------------------
// Properties
// ---------------------------------------------------------------------------

proptest! {
    #![proptest_config(ProptestConfig {
        // 256 cases is plenty for these pure-CPU invariants. The CI
        // matrix already runs 100× the basic example-based tests, so
        // we don't need a heroic case count.
        cases: 256,
        // Fail fast on shrinking — these properties shrink to the
        // empty / minimal input quickly, and we want the failure
        // surface to stay small.
        max_shrink_iters: 256,
        ..ProptestConfig::default()
    })]

    /// `UserId::parse(s).to_string() == s` and
    /// `UserId::from_str(parse(s).to_string().as_str()) == parse(s)`.
    /// This catches a `Display` impl that drops the canonical
    /// hyphenation, swaps to upper-case, or otherwise re-encodes the
    /// UUID in a way `parse` won't accept back.
    #[test]
    fn user_id_round_trips(s in uuid_string_strategy()) {
        let id = UserId::parse(&s).expect("uuid_string_strategy yields valid UUIDs");
        let displayed = id.to_string();
        prop_assert_eq!(&displayed, &s, "UserId::Display must equal the parsed string");
        let re_parsed = UserId::from_str(&displayed)
            .expect("UserId::Display output must round-trip through FromStr");
        prop_assert_eq!(re_parsed, id, "UserId round-trip lost the original value");
    }

    /// `SessionId` has the same surface as `UserId` (private inner,
    /// `new_v4()` and `parse`), so the same invariant applies. Kept
    /// as a separate property so a future divergence (e.g. `SessionId`
    /// grows a `%u` format that breaks the parity) is caught
    /// independently.
    #[test]
    fn session_id_round_trips(s in uuid_string_strategy()) {
        let id = SessionId::parse(&s).expect("uuid_string_strategy yields valid UUIDs");
        let displayed = id.to_string();
        prop_assert_eq!(&displayed, &s, "SessionId::Display must equal the parsed string");
        let re_parsed = SessionId::from_str(&displayed)
            .expect("SessionId::Display output must round-trip through FromStr");
        prop_assert_eq!(re_parsed, id, "SessionId round-trip lost the original value");
    }

    /// `Session::new(user_id, now, ttl).expires_at() == now + ttl`.
    /// This is the core time-arithmetic invariant of the Session
    /// type. A regression here (e.g. subtracting the TTL, dropping
    /// the chrono timezone, or accidentally flooring to the day)
    /// would silently invalidate every session's expiry.
    #[test]
    fn session_expires_at_is_now_plus_ttl(
        user_id in user_id_strategy(),
        now in datetime_strategy(),
        ttl in ttl_strategy(),
    ) {
        let session = Session::new(user_id, now, ttl);
        let expected = now + ttl;
        prop_assert_eq!(
            session.expires_at(),
            expected,
            "Session::new must store expires_at = now + ttl"
        );
    }

    /// A fresh session with a strictly positive TTL is not expired at
    /// its `issued_at`. (We can't assert `!is_expired()` against the
    /// real clock, but we can assert `!is_expired_at(now)` because
    /// the issued-at and now are equal in this construction path.)
    #[test]
    fn fresh_session_is_not_expired_at_issued_at(
        user_id in user_id_strategy(),
        now in datetime_strategy(),
        ttl in ttl_strategy(),
    ) {
        let session = Session::new(user_id, now, ttl);
        prop_assert!(
            !session.is_expired_at(now),
            "Session with positive TTL must not be expired at its issued_at"
        );
    }

    /// `Token::verify(Token::sign(t, s).as_str(), s) == Ok(t)`. This
    /// is the canonical "the token is unchanged by the round-trip"
    /// property. A regression that flips a sign/verify param
    /// (`sign(&self, &self.0, secret)`), or that swaps the byte
    /// order between hex-encode and hex-decode, would be caught
    /// here.
    #[test]
    fn token_sign_verify_round_trip(
        bytes in token_bytes_strategy(),
        secret in secret_strategy(),
    ) {
        let t = Token::from_bytes(bytes);
        let signed = t.sign(&secret);
        let recovered = Token::verify(&signed, &secret)
            .expect("verify with the same secret must succeed");
        prop_assert_eq!(
            recovered, t,
            "Token round-trip via sign/verify must reproduce the original bytes"
        );
    }

    /// `Token::verify(sign(t, s1), s2)` fails for any two distinct
    /// secrets `s1` and `s2`. We avoid the trivial case `s1 == s2`
    /// by requiring the lengths to differ, which is a cheap proxy
    /// for "the secrets are not equal" without needing a comparison
    /// of variable-length byte slices inside the property.
    #[test]
    fn token_verify_with_wrong_secret_fails(
        bytes in token_bytes_strategy(),
        secret_len_a in 1usize..=32,
        secret_len_b in 1usize..=32,
    ) {
        prop_assume!(secret_len_a != secret_len_b);
        let s1: Vec<u8> = vec![0xAA; secret_len_a];
        let s2: Vec<u8> = vec![0xBB; secret_len_b];
        let t = Token::from_bytes(bytes);
        let signed = t.sign(&s1);
        let result = Token::verify(&signed, &s2);
        prop_assert!(
            result.is_err(),
            "Token::verify with a different-length secret must fail (got Ok)"
        );
    }

    /// `Token::sign(t, s)` is deterministic: signing the same token
    /// twice with the same secret yields the same string. A
    /// non-deterministic HMAC (e.g. one that uses a per-call
    /// `Instant::now()` salt) would fail this property, which is
    /// the right behaviour because non-deterministic signatures
    /// break every cache and every log-dedup downstream.
    #[test]
    fn token_sign_is_deterministic(
        bytes in token_bytes_strategy(),
        secret in secret_strategy(),
    ) {
        let t = Token::from_bytes(bytes);
        let a = t.sign(&secret);
        // A "1-nanosecond tick" (spurious — sign is pure) and a
        // second sign. The output must match exactly.
        let b = t.sign(&secret);
        prop_assert_eq!(&a, &b, "Token::sign must be deterministic over the same (t, s) pair");
    }

    /// `Role::Admin.can_access(p) == true` for every `Permission`
    /// variant. This is the "admin can do anything" invariant — a
    /// regression that turns Admin into a permission list (e.g.
    /// "admin = all except FleetManage") would be caught by *all 8*
    /// cases in the proptest run, not just the 1-2 we test by hand.
    #[test]
    fn admin_can_access_everything(p in permission_strategy()) {
        prop_assert!(
            Role::Admin.can_access(&p),
            "Role::Admin must be able to access {p:?}",
            p = p,
        );
    }

    /// `Role::custom(name, perms).can_access(p) == perms.contains(&p)`.
    /// This is the closure property of the `Custom` variant: the
    /// permission set is the *only* source of truth for what a
    /// `Custom` role can do. A bug in `Role::custom`'s
    /// sort/dedup/binary-search path would be caught by the
    /// mismatched member / non-member cases.
    #[test]
    fn custom_role_can_access_matches_set(
        perms in permissions_vec_strategy(),
        p in permission_strategy(),
    ) {
        let role = Role::custom("test-role", perms.clone());
        let expected = perms.contains(&p);
        let actual = role.can_access(&p);
        prop_assert_eq!(
            actual, expected,
            "Role::custom({name:?}, _).can_access({p:?}) must equal perms.contains(&p) \
             (perms = {perms:?})",
            name = role.name(),
            p = p,
            perms = perms,
        );
    }

    /// `Role::Operator` is the middle tier: it can do everything
    /// `Admin` can do *except* `BillingRefund`. The `BillingRead`
    /// permission is still granted (operators can audit their own
    /// billing). This property pins down the matrix delta: any
    /// future PR that adds a second `Operator`-deny permission will
    /// fail here, prompting an explicit discussion.
    #[test]
    fn operator_can_access_except_billing_refund(p in permission_strategy()) {
        let expected = !matches!(p, Permission::BillingRefund);
        let actual = Role::Operator.can_access(&p);
        prop_assert_eq!(
            actual, expected,
            "Role::Operator must deny exactly BillingRefund, not {p:?}",
            p = p,
        );
    }

    /// `serde_json::from_str(serde_json::to_string(p).as_str()) == p`
    /// for every `Permission` variant. Catches a `#[serde(rename)]`
    /// regression that would silently change the on-the-wire
    /// permission format (and break every external RBAC consumer
    /// that has the old string cached).
    #[test]
    fn permission_serde_round_trip(p in permission_strategy()) {
        let json = serde_json::to_string(&p)
            .expect("Permission must serialize to JSON");
        let back: Permission = serde_json::from_str(&json)
            .expect("Permission must deserialize from its own JSON form");
        prop_assert_eq!(back, p, "Permission serde round-trip lost the value");
    }
}
